export const supportedCurrencies = [
  { code: 'SGD', symbol: 'S$', label: 'Singapore Dollar' },
  { code: 'MYR', symbol: 'RM', label: 'Malaysian Ringgit' },
  { code: 'USD', symbol: 'US$', label: 'US Dollar' },
  { code: 'EUR', symbol: '€', label: 'Euro' },
  { code: 'GBP', symbol: '£', label: 'British Pound' },
  { code: 'AUD', symbol: 'A$', label: 'Australian Dollar' },
  { code: 'CAD', symbol: 'C$', label: 'Canadian Dollar' },
  { code: 'NZD', symbol: 'NZ$', label: 'New Zealand Dollar' },
  { code: 'HKD', symbol: 'HK$', label: 'Hong Kong Dollar' },
  { code: 'JPY', symbol: '¥', label: 'Japanese Yen' },
  { code: 'CNY', symbol: 'CN¥', label: 'Chinese Yuan' },
  { code: 'KRW', symbol: '₩', label: 'South Korean Won' },
  { code: 'THB', symbol: '฿', label: 'Thai Baht' },
  { code: 'IDR', symbol: 'Rp', label: 'Indonesian Rupiah' },
  { code: 'PHP', symbol: '₱', label: 'Philippine Peso' },
  { code: 'INR', symbol: '₹', label: 'Indian Rupee' },
  { code: 'AED', symbol: 'AED', label: 'UAE Dirham' },
  { code: 'VND', symbol: '₫', label: 'Vietnamese Dong' },
  { code: 'BND', symbol: 'B$', label: 'Brunei Dollar' },
  { code: 'TWD', symbol: 'NT$', label: 'New Taiwan Dollar' },
  { code: 'PKR', symbol: '₨', label: 'Pakistani Rupee' },
  { code: 'BDT', symbol: '৳', label: 'Bangladeshi Taka' },
  { code: 'LKR', symbol: 'Rs', label: 'Sri Lankan Rupee' },
  { code: 'NPR', symbol: 'रू', label: 'Nepalese Rupee' },
  { code: 'MMK', symbol: 'K', label: 'Myanmar Kyat' },
  { code: 'KHR', symbol: '៛', label: 'Cambodian Riel' },
  { code: 'LAK', symbol: '₭', label: 'Lao Kip' },
  { code: 'MNT', symbol: '₮', label: 'Mongolian Tugrik' },
  { code: 'KZT', symbol: '₸', label: 'Kazakhstani Tenge' },
  { code: 'UZS', symbol: 'soʻm', label: 'Uzbekistani Som' },
  { code: 'SAR', symbol: 'SAR', label: 'Saudi Riyal' },
  { code: 'QAR', symbol: 'QAR', label: 'Qatari Riyal' },
  { code: 'KWD', symbol: 'KWD', label: 'Kuwaiti Dinar' },
  { code: 'BHD', symbol: 'BHD', label: 'Bahraini Dinar' },
  { code: 'OMR', symbol: 'OMR', label: 'Omani Rial' },
  { code: 'JOD', symbol: 'JOD', label: 'Jordanian Dinar' },
  { code: 'ILS', symbol: '₪', label: 'Israeli New Shekel' },
  { code: 'TRY', symbol: '₺', label: 'Turkish Lira' },
  { code: 'EGP', symbol: 'E£', label: 'Egyptian Pound' },
  { code: 'ZAR', symbol: 'R', label: 'South African Rand' },
  { code: 'NGN', symbol: '₦', label: 'Nigerian Naira' },
  { code: 'KES', symbol: 'KSh', label: 'Kenyan Shilling' },
  { code: 'GHS', symbol: 'GH₵', label: 'Ghanaian Cedi' },
  { code: 'TZS', symbol: 'TSh', label: 'Tanzanian Shilling' },
  { code: 'UGX', symbol: 'USh', label: 'Ugandan Shilling' },
  { code: 'MAD', symbol: 'MAD', label: 'Moroccan Dirham' },
  { code: 'DZD', symbol: 'DZD', label: 'Algerian Dinar' },
  { code: 'TND', symbol: 'TND', label: 'Tunisian Dinar' },
  { code: 'ETB', symbol: 'Br', label: 'Ethiopian Birr' },
  { code: 'XOF', symbol: 'CFA', label: 'West African CFA Franc' },
  { code: 'XAF', symbol: 'FCFA', label: 'Central African CFA Franc' },
  { code: 'CHF', symbol: 'CHF', label: 'Swiss Franc' },
  { code: 'SEK', symbol: 'kr', label: 'Swedish Krona' },
  { code: 'NOK', symbol: 'kr', label: 'Norwegian Krone' },
  { code: 'DKK', symbol: 'kr', label: 'Danish Krone' },
  { code: 'PLN', symbol: 'zł', label: 'Polish Zloty' },
  { code: 'CZK', symbol: 'Kč', label: 'Czech Koruna' },
  { code: 'HUF', symbol: 'Ft', label: 'Hungarian Forint' },
  { code: 'RON', symbol: 'lei', label: 'Romanian Leu' },
  { code: 'BGN', symbol: 'лв', label: 'Bulgarian Lev' },
  { code: 'ISK', symbol: 'kr', label: 'Icelandic Krona' },
  { code: 'RSD', symbol: 'дин', label: 'Serbian Dinar' },
  { code: 'UAH', symbol: '₴', label: 'Ukrainian Hryvnia' },
  { code: 'RUB', symbol: '₽', label: 'Russian Ruble' },
  { code: 'GEL', symbol: '₾', label: 'Georgian Lari' },
  { code: 'BRL', symbol: 'R$', label: 'Brazilian Real' },
  { code: 'MXN', symbol: 'MX$', label: 'Mexican Peso' },
  { code: 'ARS', symbol: 'AR$', label: 'Argentine Peso' },
  { code: 'CLP', symbol: 'CL$', label: 'Chilean Peso' },
  { code: 'COP', symbol: 'COL$', label: 'Colombian Peso' },
  { code: 'PEN', symbol: 'S/', label: 'Peruvian Sol' },
  { code: 'UYU', symbol: '$U', label: 'Uruguayan Peso' },
  { code: 'BOB', symbol: 'Bs', label: 'Bolivian Boliviano' },
  { code: 'PYG', symbol: '₲', label: 'Paraguayan Guarani' },
  { code: 'CRC', symbol: '₡', label: 'Costa Rican Colon' },
  { code: 'DOP', symbol: 'RD$', label: 'Dominican Peso' },
  { code: 'JMD', symbol: 'J$', label: 'Jamaican Dollar' },
] as const;

export function currencySymbol(code: string) {
  return supportedCurrencies.find((currency) => currency.code === code)?.symbol || code;
}
